TASK05: Hello Kernel Module
Kernel-GL-HRK/gl_kernel_BaseCamp_2022_II pull request #96
Opened 2023-03-01 20:44 UTC by saurier

Create hello.c with greetings, bye-message and simple calculator. With module parameters user can enter two operators for sum, sub and mul functions.

2023-03-10 20:03 UTC, saurier commented
TASK7: Led Blinking driver
Create hello.c with simple calculator and gpio LED functionality.

2023-03-12 18:00 UTC, AndriySmolskyy commented on task5-hello-module/hello.c
> +pr_info("HELLO: Hello, world!\nCalculations:\n");
Something went wrong with formatting here and below

2023-03-17 10:23 UTC, AndriySmolskyy commented on task6-hello-module-procfs/hello.c
> +	not_copied = copy_to_user(buffer, procfs_buffer, to_copy);
Per my understanding, if `procfs_buffer_size` variable is maintained and updated in the code below it is assumed that `procfs_buffer` contents can be read by the user space app by multiple reads.
For example 100 bytes buffer can be read by 2 `hello_read` calls with count set to 25 and 75.
But, data is copied to the user provided buffer from the beginning of the `procfs_buffer`, so the same data will be copied twice, what, per my understanding, is not expected.

2023-03-17 10:25 UTC, AndriySmolskyy commented on task6-hello-module-procfs/hello.c
> +		proc_remove(proc_file);
No sense to call `proc_remove(proc_file);` because `proc_file` is not valid (it contains an error code)

2023-03-17 10:26 UTC, AndriySmolskyy commented on task7-LedDriver/hello.c
> +procfs_buffer_size = strlen(procfs_buffer);
Code style issues are here and below.

2023-03-17 10:30 UTC, AndriySmolskyy commented on task7-LedDriver/hello.c
> +	not_copied = copy_to_user(buffer, procfs_buffer, to_copy);
Data is copied always from the beginning of the buffer.
Please see my comment in the same location in task6-hello-module-procfs/hello.c

2023-03-17 10:48 UTC, AndriySmolskyy commented on task7-LedDriver/hello.c
> +MODULE_AUTHOR("Maksym Khomenko"); ///< The author -- visible when you use modinfo
????

2023-03-17 10:51 UTC, AndriySmolskyy commented on task7-LedDriver/hello.c
> +		proc_remove(proc_file);
No sense to call `proc_remove(proc_file);` as `proc_file` is not valid.

2023-03-17 11:02 UTC, AndriySmolskyy requested changes
Please see my comment in files.
Also, it would be great to create a separate pull request for each task with possibly to merge them separately.

2023-05-05 07:56 UTC, AndriySmolskyy commented on task6-hello-module-procfs/hello.c
> +	if (copy_to_user(buffer, procfs_buffer, procfs_buffer_size))
In general here can be a case when calling user space application might provide buffer smaller then "procfs_buffer_size", so copy_to_user call will corrupt some other data.

2023-05-05 08:03 UTC, merged